/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_esialb_edison_sfo_SFOled */

#ifndef _Included_org_esialb_edison_sfo_SFOled
#define _Included_org_esialb_edison_sfo_SFOled
#ifdef __cplusplus
extern "C" {
#endif
#undef org_esialb_edison_sfo_SFOled_BUFFER_SIZE
#define org_esialb_edison_sfo_SFOled_BUFFER_SIZE 384L
#undef org_esialb_edison_sfo_SFOled_WIDTH
#define org_esialb_edison_sfo_SFOled_WIDTH 64L
#undef org_esialb_edison_sfo_SFOled_HEIGHT
#define org_esialb_edison_sfo_SFOled_HEIGHT 48L
/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    isUpPressed0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esialb_edison_sfo_SFOled_isUpPressed0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    isDownPressed0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esialb_edison_sfo_SFOled_isDownPressed0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    isLeftPressed0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esialb_edison_sfo_SFOled_isLeftPressed0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    isRightPressed0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esialb_edison_sfo_SFOled_isRightPressed0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    isSelectPressed0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esialb_edison_sfo_SFOled_isSelectPressed0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    isAPressed0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esialb_edison_sfo_SFOled_isAPressed0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    isBPressed0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_esialb_edison_sfo_SFOled_isBPressed0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    begin0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_esialb_edison_sfo_SFOled_begin0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    invert0
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_esialb_edison_sfo_SFOled_invert0
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    display0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_esialb_edison_sfo_SFOled_display0
  (JNIEnv *, jclass);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    write0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_esialb_edison_sfo_SFOled_write0
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_esialb_edison_sfo_SFOled
 * Method:    read0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_esialb_edison_sfo_SFOled_read0
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
